import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  header: {
    fontSize: 22,
    fontWeight: "700",
    color: "white",
    marginVertical: 10,
    textAlign: "center",
  },
  gridContainer: {
    paddingBottom: 80,
  },
  columnWrapper: {
    justifyContent: "flex-start", // ✅ keeps alignment neat
    marginBottom: 20,
    gap: 3,
  },
  productCard: {
    backgroundColor: "#b1bfd3",
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
    marginTop: 10,
    overflow: "hidden",
  },
  productImage: {
    width: "100%",
    height: 280,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
  },
  productInfo: {
    padding: 12,
  },
  productName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#111",
    marginBottom: 4,
  },
  productDetails: {
    fontSize: 14,
    color: "#555",
  },
  productQuantity: {
    fontSize: 13,
    color: "#777",
    marginTop: 4,
  },
  productDescription: {
    fontSize: 13,
    color: "#666",
    marginTop: 6,
  },
  actionButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 12,
  },
  editButton: {
    backgroundColor: "#3498db",
    color: "#fff",
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 8,
    fontWeight: "500",
    overflow: "hidden",
  },
  deleteButton: {
    backgroundColor: "#e74c3c",
    color: "#fff",
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 8,
    fontWeight: "500",
    overflow: "hidden",
  },
  searchContainer: {
    width: "100%",
    alignSelf: "center",
    marginBottom: 16,
    backgroundColor: "#111",
    borderRadius: 12,
    borderColor: "#333",
    borderWidth: 1,
  },
  searchInput: {
    color: "#fff",
    fontSize: 18,
    width: "100%",
    paddingHorizontal: 16,
    paddingVertical: 15,
  },
  emptyText: {
    textAlign: "center",
    color: "#aaa",
    marginTop: 40,
    fontSize: 16,
    fontStyle: "italic",
  },
  designsIndicator: {
  backgroundColor: '#3498db',
  paddingHorizontal: 8,
  paddingVertical: 4,
  borderRadius: 12,
  alignSelf: 'flex-start',
  marginTop: 4,
},
designsIndicatorText: {
  color: '#fff',
  fontSize: 12,
  fontWeight: '500',
},

// Modal Styles
modalOverlay: {
  flex: 1,
  backgroundColor: 'rgba(0, 0, 0, 0.6)',
  justifyContent: 'center',
  alignItems: 'center',
  padding: 20,
},
modalContainer: {
  backgroundColor: '#fff',
  borderRadius: 16,
  width: 'auto',
  maxHeight: '70%',
  shadowColor: '#000',
  shadowOffset: {
    width: 0,
    height: 2,
  },
  shadowOpacity: 0.25,
  shadowRadius: 4,
  elevation: 5,
},
modalHeader: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  padding: 20,
  borderBottomWidth: 1,
  borderBottomColor: '#ecf0f1',
},
modalTitle: {
  fontSize: 18,
  fontWeight: 'bold',
  color: '#2c3e50',
  flex: 1,
},
closeButton: {
  width: 30,
  height: 30,
  borderRadius: 15,
  backgroundColor: '#e74c3c',
  justifyContent: 'center',
  alignItems: 'center',
},
closeButtonText: {
  color: '#fff',
  fontSize: 18,
  fontWeight: 'bold',
  lineHeight: 20,
},
designsContainer: {
  padding: 16,
  minHeight: 200,
},
horizontalDesignsList: {
  paddingVertical: 8,
  paddingHorizontal: 4,
},
designItemHorizontal: {
  alignItems: 'center',
  backgroundColor: '#f8f9fa',
  padding: 16,
  borderRadius: 12,
  marginHorizontal: 8,
  borderWidth: 1,
  borderColor: '#e9ecef',
  width: 140,
},
designImageHorizontal: {
  width: 100,
  height: 100,
  borderRadius: 8,
  marginBottom: 8,
},
designInfoHorizontal: {
  alignItems: 'center',
},
designTitle: {
  fontSize: 14,
  fontWeight: '600',
  color: '#2c3e50',
  marginBottom: 4,
  textAlign: 'center',
},
designStock: {
  fontSize: 12,
  color: '#27ae60',
  fontWeight: '500',
  textAlign: 'center',
},
noDesignsText: {
  textAlign: 'center',
  fontSize: 16,
  color: '#7f8c8d',
  fontStyle: 'italic',
  padding: 40,
},
modalFooter: {
  padding: 20,
  borderTopWidth: 1,
  borderTopColor: '#ecf0f1',
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
},
totalStock: {
  fontSize: 16,
  fontWeight: '600',
  color: '#2c3e50',
},
editAllButton: {
  backgroundColor: '#3498db',
  paddingHorizontal: 16,
  paddingVertical: 8,
  borderRadius: 8,
},
editAllButtonText: {
  color: '#fff',
  fontSize: 14,
  fontWeight: '500',
},

// Remove or keep the old vertical styles if needed elsewhere
designItem: {
  flexDirection: 'row',
  alignItems: 'center',
  backgroundColor: '#f8f9fa',
  padding: 12,
  borderRadius: 12,
  marginBottom: 12,
  borderWidth: 1,
  borderColor: '#e9ecef',
},
designImage: {
  width: 60,
  height: 60,
  borderRadius: 8,
  marginRight: 12,
},
designInfo: {
  flex: 1,
},  
});
